/** Auto-generated by npm run seed:demo — do not edit assigneeId by hand. */
export const DEMO_TEAM_OPTIONS = [
  { teamId: '', label: 'All Teams' },
  { teamId: 'Frontend', label: 'Frontend' },
  { teamId: 'Backend', label: 'Backend' },
] as const;

export const DEMO_ASSIGNEE_PRESETS = [
  {
    key: 'sara-frontend',
    label: 'Sara — Frontend',
    assigneeName: 'Sara',
    assigneeId: 'b04ca9dc-e021-70b9-beb4-e6da6988da10',
    teamId: 'Frontend',
  },
  {
    key: 'omar-backend',
    label: 'Omar — Backend',
    assigneeName: 'Omar',
    assigneeId: '90ec09ac-90e1-7062-1b28-358c6c7159be',
    teamId: 'Backend',
  },
] as const;
